HospitalMS/Models/PatientModes/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HospitalMS.Models.PatientModes
{
    public class Patient
    {
        public int? Id { get; set; }
        [Display(Name = "name")]
        public string PersonId { get; set; }
        [Display(Name = "Problem Category")]
        public int? ProblemCategoryId { get; set; }
        public string ProblemDescription { get; set; }
        [Display(Name = "Employee namename")]
        public int? EmployeId { get; set; }

        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }
        public string PhotoPath { get; set; }

        public int? IUser { get; set; }
        public DateTime? IDate { get; set; }
        public int? EUser { get; set; }
        public DateTime? EDate { get; set; }

        public List<PatientView> PatientList { get; set; }
    }
    public class PatientView
    {
        public int? Id { get; set; }

        public string PersonId { get; set; }
        public int? SpecialtyId { get; set; }
        public int? PositionId { get; set; }
        [Column(TypeName = "decimal(18,3)")]
        public decimal? Salary { get; set; }
        public string PhotoPath { get; set; }
        [NotMapped]
        public string Name { get; set; }
        [NotMapped]
        public string PersonName { get; set; }
        [Display(Name = "Employee namename")]
        public int? EmployeId { get; set; }
        [Display(Name = "Problem Category")]
        public int? ProblemCategoryId { get; set; }
        public string ProblemDescription { get; set; }
        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }
    }
}

HospitalMS/Controllers/EmployeesController.cs
using HospitalMS.Data;
using HospitalMS.Models.AccountModels;
using HospitalMS.Models.DoctorScheduleModels;
using HospitalMS.Models.EmployeeModels;
using HospitalMS.Models.PersonModels;
using HospitalMS.Models.PositionModels;
using HospitalMS.Models.SpecialityModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static HospitalMS.Models.DoctorScheduleModels.DoctorsSchedule;

namespace HospitalMS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IPersonRepository _personRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly ISpecialityRepository _specialityRepository;
        private readonly IPositionRepository _positionRepository;
        private readonly IDoctorsScheduleRepository _doctorsScheduleRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public EmployeesController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IEmployeeRepository employeeRepository, IHostingEnvironment hostingEnvironment, IPersonRepository personRepository, IAccountRepository accountRepository, ISpecialityRepository specialityRepository, IPositionRepository positionRepository, IDoctorsScheduleRepository doctorsScheduleRepository)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.hostingEnvironment = hostingEnvironment;
            _personRepository = personRepository;
            _employeeRepository = employeeRepository;
            _accountRepository = accountRepository;
            _specialityRepository = specialityRepository;
            _positionRepository = positionRepository;
            _doctorsScheduleRepository = doctorsScheduleRepository;
        }
        public IActionResult Index()
        {
            //List<ApplicationUser> person = _accountRepository.GetAllPerson().ToList();

            //List<Employee> employee = _employeeRepository.GetAllEmployees().ToList();
            //var model = _employeeRepository.GetAllEmployees();
            Employee model = new Employee();
            List<EmployeeView> empList = (from e in _employeeRepository.GetAllEmployees()
                                          join p in _accountRepository.GetAllPerson() on e.PersonId equals p.Id
                                          select new EmployeeView
                                          {
                                              Id = e.Id,
                                              PersonId = e.PersonId,
                                              PositionId = e.PositionId,
                                              Name = p.Name,
                                              PhotoPath = e.PhotoPath
                                          }).ToList();
            // var model = _employeeRepository.GetAllEmployees();
            model.EmployeeList = empList;
            return View(model);
        }

        public ViewResult Details(int id, string personid, int positionid)
        {
            EmployeeViewModel employeeViewModel = new EmployeeViewModel()
            {
                Person = _employeeRepository.GetPerson(personid),
                Employee = _employeeRepository.GetEmployee(id),
                Position = _employeeRepository.GetPosition(positionid),
                PageTitle = "Employee Details"
            };

            return View(employeeViewModel);
        }




        [HttpGet]
        [AllowAnonymous]
        public ViewResult Create()
        {
            //List<ApplicationUser> li = new List<ApplicationUser>();
            //li = _context.AspNetUsers.ToList();
            //ViewBag.PersonList = li;
            ViewBag.PersonList = _accountRepository.GetAllPerson().OrderBy(x =>x.Name).ToList();
            ViewBag.SpecialityList = _specialityRepository.GetAllSpeciality().OrderBy(x => x.Name).ToList();
            ViewBag.PositionList = _positionRepository.GetAllPosition().OrderBy(x => x.PositionName).ToList();
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Create(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {

                string uniqueFileName = null;

                if (model.Photo != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Employee newEmployee = new Employee
                {
                    PersonId = model.PersonId,
                    SpecialtyId = model.SpecialtyId,
                    PositionId = model.PositionId,
                    Salary = model.Salary,
                    IUser = 1,
                    IDate = DateTime.Now,
                    EUser = 0,
                    EDate = null,

                    PhotoPath = uniqueFileName
                };

                _employeeRepository.Add(newEmployee);
                return RedirectToAction("details", new { id = newEmployee.Id, personid = newEmployee.PersonId, positionid = newEmployee.PositionId });
            }

            return View();
        }

        [HttpGet]
        public ViewResult Edit(int id, string personid, int positionid)
        {
            Employee employee = _employeeRepository.GetEmployee(id);
            ApplicationUser person = _employeeRepository.GetPerson(personid);
            Position position = _employeeRepository.GetPosition(positionid);
            EmployeeViewModel employeeEditViewModel = new EmployeeViewModel
            {
                Name = person.Name,
                Email = person.Email,
                PhoneNumber = person.PhoneNumber,
                BirthDate = person.BirthDate,
                BloodGroup = person.BloodGroup,
                PresentAddress = person.PresentAddress,
                PermanentAddress = person.PermanentAddress,
                Id = employee.Id,
                PersonId = employee.PersonId,
                SpecialtyId = employee.SpecialtyId,
                PositionId = employee.PositionId,
                Salary = employee.Salary,

                ExistingPhotoPath = employee.PhotoPath
            };
            return View(employeeEditViewModel);
        }

        [HttpPost]
        public IActionResult Edit(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                Employee employee = _employeeRepository.GetEmployee(model.Id);
                ApplicationUser person = _employeeRepository.GetPerson(model.PersonId);
                Position position = _employeeRepository.GetPosition(model.PositionId);
                person.Name = model.Name;
                person.Email = model.Email;
                person.PhoneNumber = model.PhoneNumber;
                person.Gender = model.Gender;
                person.BloodGroup = model.BloodGroup;
                person.BirthDate = model.BirthDate;
                person.PresentAddress = model.PresentAddress;
                person.PermanentAddress = model.PermanentAddress;
                employee.PositionId = model.PositionId;
                employee.PersonId = model.PersonId;
                employee.SpecialtyId = model.SpecialtyId;
                employee.Salary = model.Salary;
                employee.EDate = DateTime.Now;
                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                            "images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }

                    employee.PhotoPath = ProcessUploadedFile(model);
                }

                Employee updatedEmployee = _employeeRepository.Update(employee);
                ApplicationUser updatedPerson = _accountRepository.Update(person);
                //Position updatePosition = _positionRepository.Update(position);

                return RedirectToAction("Index");
            }
            return View(model);
        }
        ///// ekhane image path rename
        private string ProcessUploadedFile(EmployeeViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        #region Doctor Shedule
        [HttpGet]
        [AllowAnonymous]
        public ViewResult CreateDoctorShedule()
        {
            ViewBag.EmployeeList = (from p in _accountRepository.GetAllPerson()
                                    join e in _employeeRepository.GetAllEmployees() on p.Id equals e.PersonId
                                    select new EmployeeViewModel

HospitalMS/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HospitalMS.Models.AccountModels;
using HospitalMS.Models.EmployeeModels;
using HospitalMS.Models.PatientModes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using static HospitalMS.Models.PatientModes.Patient;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HospitalMS.Controllers
{
    public class PatientsController : Controller
    {
        private readonly IPatientRepository _patientRepository;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IAccountRepository _accountRepository;

        public PatientsController(IPatientRepository patientRepository, IHostingEnvironment hostingEnvironment, IEmployeeRepository employeeRepository, IAccountRepository accountRepository)
        {
            _patientRepository = patientRepository;
            this.hostingEnvironment = hostingEnvironment;
            _employeeRepository = employeeRepository;
            _accountRepository = accountRepository;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            Patient model = new Patient();
            List<PatientView> patientList = (from e in _employeeRepository.GetAllEmployees() 
                                             join pa in _patientRepository.GetAllPatient() on e.Id equals pa.EmployeId
                                             join p in _accountRepository.GetAllPerson() on pa.PersonId equals p.Id
                                             select new PatientView
                                             {
                                                 Id = pa.Id,
                                                 PersonId = pa.PersonId,
                                                 EmployeId = pa.EmployeId,
                                                 ProblemCategoryId = pa.ProblemCategoryId,
                                                 ProblemDescription = pa.ProblemDescription,
                                                 Date = pa.Date,
                                                 Name = p.Name,
                                                 PhotoPath = pa.PhotoPath
                                             }).ToList();
            //var model = _patientRepository.GetAllPatient();
            model.PatientList = patientList;
            return View(model);
        }
        [AllowAnonymous]
        public ViewResult Details(int id)
        {
            PatientViewModel patientViewModel = new PatientViewModel()
            {
                Patient = _patientRepository.GetPatient(id),
                PageTitle = "Patient Details"
            };

            return View(patientViewModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public ViewResult Create()
        {
            Patient patient = new Patient();
            ApplicationUser user = new ApplicationUser();
            ViewBag.PersonList = _accountRepository.GetAllPerson().OrderBy(x => x.IDate).ToList();
            ViewBag.EmployeeList = _employeeRepository.GetAllEmployees().OrderBy(x => x.Name).ToList();
            ViewBag.problemList = _employeeRepository.GetAllEmployees().OrderBy(x => x.Name).ToList();
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Create(PatientViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (model.Photo != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Patient newPatient = new Patient
                {
                    PersonId = model.PersonId,
                    ProblemCategoryId = model.ProblemCategoryId,
                    ProblemDescription = model.ProblemDescription,
                    EmployeId = model.EmployeId,
                    Date = model.Date,
                    IUser = 1,
                    IDate = DateTime.Now,
                    EUser = 0,
                    EDate = null,

                    PhotoPath = uniqueFileName
                };

                _patientRepository.Add(newPatient);
                return RedirectToAction("details", new { id = newPatient.Id });
            }

            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ViewResult Edit(int id)
        {

            Patient patient = _patientRepository.GetPatient(id);
            PatientViewModel patientViewModel = new PatientViewModel
            {
                Ids = patient.Id,
                PersonId = patient.PersonId,
                ProblemCategoryId = patient.ProblemCategoryId,
                ProblemDescription = patient.ProblemDescription,
                EmployeId = patient.EmployeId,
                Date = patient.Date,

                ExistingPhotoPath = patient.PhotoPath
            };
            return View(patientViewModel);
        }
    }
}

HospitalMS/Views/Patients/Create.cshtml
@model PatientViewModel


@{
    ViewBag.Title = "Create Employee";
}

<form enctype="multipart/form-data" asp-controller="Patients" asp-action="create" method="post" class="mt-3">
    <div class="form-group row">
        <div class="col-sm-6">
            <div class="row">
                <label asp-for="PersonId" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-7">
                    <select asp-for="PersonId" class="custom-select mr-sm-2"
                            asp-items="@(new SelectList(@ViewBag.PersonList,"Id","Name"))">
                        @*<option value="">Please Select</option>*@
                    </select>
                    @*<span asp-validation-for="Gender" class="text-danger"></span>*@
                </div>
            </div>
        </div>
    </div>
    @*<div class="form-group row">
        <label asp-for="ProblemCategoryId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ProblemCategoryId" class="form-control" placeholder="ProblemCategory" />
            <span asp-validation-for="ProblemCategoryId" class="text-danger"></span>
        </div>
    </div>*@

    <div class="form-group row">
        <label asp-for="ProblemDescription" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ProblemDescription" class="form-control" placeholder="ProblemDescription" />
            <span asp-validation-for="ProblemDescription" class="text-danger"></span>
        </div>
    </div>
    @*<div class="form-group row">
        <label asp-for="EmployeId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="PersonId" class="custom-select mr-sm-2"
                    asp-items="@(new SelectList(@ViewBag.EmployeeList,"Id","Name"))">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="EmployeId" class="text-danger"></span>
        </div>
    </div>*@

    @*<div class="form-group row">
            <label asp-for="EmpCatId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="EmpCatId" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<EmployeeCategor>()">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="EmpCatId" class="text-danger"></span>
            </div>
        </div>*@
    <div class="form-group row">
        <label asp-for="Date" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Date" class="form-control" placeholder="Date" readonly="@false" value="@DateTime.Now" />

        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="form-control custom-file-input" />
                <label class="custom-file-label">Choose File...</label>
            </div>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </div>

    @section Scripts {
        <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(fileName);
                    });
                });
        </script>
    }

</form>

HospitalMS/Views/Patients/Details.cshtml
@model PatientViewModel

@{
    ViewBag.Title = "Patrient List";
    var photoPath = "~/images/" + (Model.Patient.PhotoPath ?? "noimage.jpg");
}

<h3>@Model.PageTitle</h3>

<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.Patient.PersonId</h1>
            </div>

            <div class="card-body text-center">
                <img class="card-img-top" src="@photoPath" asp-append-version="true" style="height:100px; width:100px;" />

                <h4>Employee ID: @Model.Patient.ProblemCategoryId</h4>
                <h4>Email: @Model.Patient.ProblemDescription</h4>
                <h4>Email: @Model.Patient.EmployeId</h4>
                <h4>JoiningDate: @Model.Patient.Date</h4>
                <h4>Department: @Model.Patient.PhotoPath</h4>

            </div>
            <div class="card-footer text-center">
                <a asp-controller="Employees" asp-action="index" class="btn btn-primary">Back</a>
                <a asp-controller="Employees" asp-action="Edit" asp-route-id="@Model.Patient.Id" class="btn btn-primary">Edit</a>
            </div>
        </div>
    </div>
</div>

@*<div>
        Name : @Model.Employee.Name
    </div>
    <div>
        Email : @Model.Employee.Email
    </div>
    <div>
        Department : @Model.Employee.Department
    </div>*@


@section Scripts{

    <script src="~/js/CustomScript.js"></script>

}

HospitalMS/Views/Patients/Edit.cshtml
@model PatientViewModel


@{
    ViewBag.Title = "Edit Patient";
    var photoPath = "~/images/" + (Model.ExistingPhotoPath ?? "noimage.jpg");
}

<form enctype="multipart/form-data" asp-controller="Employees" asp-action="Edit" method="post" class="mt-3">
    <div class="form-group row">
        <input hidden asp-for="Id" />
        <input hidden asp-for="Ids" />
        <input hidden asp-for="ExistingPhotoPath" />
        <label asp-for="PersonId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="PersonId" class="form-control" placeholder="Name" />
            <span asp-validation-for="PersonId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ProblemCategoryId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ProblemCategoryId" class="form-control" placeholder="ProblemCategory" />
            <span asp-validation-for="ProblemCategoryId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="ProblemDescription" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ProblemDescription" class="form-control" placeholder="ProblemDescription" />
            <span asp-validation-for="ProblemDescription" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EmployeId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="EmployeId" class="form-control" placeholder="EmployeeId" />
            <span asp-validation-for="EmployeId" class="text-danger"></span>
        </div>
    </div>
    @*<div class="form-group row">
            <label asp-for="EmpCatId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="EmpCatId" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<EmployeeCategor>()">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="EmpCatId" class="text-danger"></span>
            </div>
        </div>*@
    <div class="form-group row">
        <label asp-for="Date" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Date" class="form-control" placeholder="Date" value="@DateTime.Now" />

        </div>
    </div>



    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="form-control custom-file-input" />
                <label class="custom-file-label">Click here to change Photo</label>
            </div>
        </div>
    </div>

    @*Display the existing employee photo*@
    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Upate</button>
            <a asp-controller="Employees" asp-action="index" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    @section Scripts {
        <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(fileName);
                    });
                });
        </script>
    }

</form>

HospitalMS/Views/Patients/Index.cshtml
@model Patient
@{
    ViewBag.Title = "Patient List";
}

<div>
    <a asp-controller="Patients" asp-action="Create" type="button" class="btn btn-primary btn-lg btn-block m-2" style="width:300px;">Create New Patient </a>


    <div class="card-deck">
        @foreach (var patient in Model.PatientList)
        {
            var photoPath = "~/images/" + (patient.PhotoPath ?? "noimage.jpg");
            <div class="card m-3" style="min-width:18rem; max-width:30.5px;">
                <div class="card-header">
                    <h3 hidden>@patient.PersonId</h3>
                    <h3 hidden>@patient.ProblemCategoryId</h3>
                    <h3 hidden>@patient.EmployeId</h3>
                    <h3>@patient.Date</h3>
                    <h3>@patient.Name</h3>
                </div>
              
                
                <img class="card-img-top imageThumbnail" src="@photoPath" asp-append-version="true" />
                <div class="card-header">
                    <h3>@patient.ProblemDescription</h3>
                </div>
                <div class="card-footer text-center">
                    <a asp-controller="Employees" asp-action="Details" asp-route-id="@patient.Id" class="btn btn-primary m-1">View</a>
                    <a asp-controller="Employees" asp-action="Edit" asp-route-id="@patient.Id" class="btn btn-primary m-1">Edit</a>
                </div>
            </div>
        }
    </div>
</div>