HospitalMS/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HospitalMS.Models.AccountModels;
using HospitalMS.Models.DoctorScheduleModels;
using HospitalMS.Models.EmployeeModels;
using HospitalMS.Models.PersonModels;
using HospitalMS.Models.PositionModels;
using HospitalMS.Models.SpecialityModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HospitalMS.Controllers
{
    public class DoctorController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IPersonRepository _personRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly ISpecialityRepository _specialityRepository;
        private readonly IPositionRepository _positionRepository;
        private readonly IDoctorsScheduleRepository _doctorsScheduleRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IHostingEnvironment hostingEnvironment;
        public DoctorController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IEmployeeRepository employeeRepository, IHostingEnvironment hostingEnvironment, IPersonRepository personRepository, IAccountRepository accountRepository, ISpecialityRepository specialityRepository, IPositionRepository positionRepository, IDoctorsScheduleRepository doctorsScheduleRepository)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.hostingEnvironment = hostingEnvironment;
            _personRepository = personRepository;
            _employeeRepository = employeeRepository;
            _accountRepository = accountRepository;
            _specialityRepository = specialityRepository;
            _positionRepository = positionRepository;
            _doctorsScheduleRepository = doctorsScheduleRepository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Prescription()
        {
            return View();
        }


    }
}

HospitalMS/Controllers/EmployeesController.cs
using HospitalMS.Data;
using HospitalMS.Models.AccountModels;
using HospitalMS.Models.DoctorScheduleModels;
using HospitalMS.Models.EmployeeModels;
using HospitalMS.Models.PersonModels;
using HospitalMS.Models.PositionModels;
using HospitalMS.Models.SpecialityModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static HospitalMS.Models.DoctorScheduleModels.DoctorsSchedule;

namespace HospitalMS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IPersonRepository _personRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly ISpecialityRepository _specialityRepository;
        private readonly IPositionRepository _positionRepository;
        private readonly IDoctorsScheduleRepository _doctorsScheduleRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public EmployeesController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IEmployeeRepository employeeRepository, IHostingEnvironment hostingEnvironment, IPersonRepository personRepository, IAccountRepository accountRepository, ISpecialityRepository specialityRepository, IPositionRepository positionRepository, IDoctorsScheduleRepository doctorsScheduleRepository)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.hostingEnvironment = hostingEnvironment;
            _personRepository = personRepository;
            _employeeRepository = employeeRepository;
            _accountRepository = accountRepository;
            _specialityRepository = specialityRepository;
            _positionRepository = positionRepository;
            _doctorsScheduleRepository = doctorsScheduleRepository;
        }
        public IActionResult Index()
        {
            //List<ApplicationUser> person = _accountRepository.GetAllPerson().ToList();

            //List<Employee> employee = _employeeRepository.GetAllEmployees().ToList();
            //var model = _employeeRepository.GetAllEmployees();
            Employee model = new Employee();
            List<EmployeeView> empList = (from e in _employeeRepository.GetAllEmployees()
                                          join p in _accountRepository.GetAllPerson() on e.PersonId equals p.Id
                                          select new EmployeeView
                                          {
                                              Id = e.Id,
                                              PersonId = e.PersonId,
                                              PositionId = e.PositionId,
                                              Name = p.Name,
                                              PhotoPath = e.PhotoPath
                                          }).ToList();
            // var model = _employeeRepository.GetAllEmployees();
            model.EmployeeList = empList;
            return View(model);
        }

        public ViewResult Details(int id, string personid, int positionid)
        {
            EmployeeViewModel employeeViewModel = new EmployeeViewModel()
            {
                Person = _employeeRepository.GetPerson(personid),
                Employee = _employeeRepository.GetEmployee(id),
                Position = _employeeRepository.GetPosition(positionid),
                PageTitle = "Employee Details"
            };

            return View(employeeViewModel);
        }




        [HttpGet]
        [AllowAnonymous]
        public ViewResult Create()
        {
            //List<ApplicationUser> li = new List<ApplicationUser>();
            //li = _context.AspNetUsers.ToList();
            //ViewBag.PersonList = li;
            ViewBag.PersonList = _accountRepository.GetAllPerson().OrderBy(x =>x.Name).ToList();
            ViewBag.SpecialityList = _specialityRepository.GetAllSpeciality().OrderBy(x => x.Name).ToList();
            ViewBag.PositionList = _positionRepository.GetAllPosition().OrderBy(x => x.PositionName).ToList();
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Create(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {

                string uniqueFileName = null;

                if (model.Photo != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Employee newEmployee = new Employee
                {
                    PersonId = model.PersonId,
                    SpecialtyId = model.SpecialtyId,
                    PositionId = model.PositionId,
                    Salary = model.Salary,
                    IUser = 1,
                    IDate = DateTime.Now,
                    EUser = 0,
                    EDate = null,

                    PhotoPath = uniqueFileName
                };

                _employeeRepository.Add(newEmployee);
                return RedirectToAction("details", new { id = newEmployee.Id, personid = newEmployee.PersonId, positionid = newEmployee.PositionId });
            }

            return View();
        }

        [HttpGet]
        public ViewResult Edit(int id, string personid, int positionid)
        {
            Employee employee = _employeeRepository.GetEmployee(id);
            ApplicationUser person = _employeeRepository.GetPerson(personid);
            Position position = _employeeRepository.GetPosition(positionid);
            EmployeeViewModel employeeEditViewModel = new EmployeeViewModel
            {
                Name = person.Name,
                Email = person.Email,
                PhoneNumber = person.PhoneNumber,
                BirthDate = person.BirthDate,
                BloodGroup = person.BloodGroup,
                PresentAddress = person.PresentAddress,
                PermanentAddress = person.PermanentAddress,
                Id = employee.Id,
                PersonId = employee.PersonId,
                SpecialtyId = employee.SpecialtyId,
                PositionId = employee.PositionId,
                Salary = employee.Salary,

                ExistingPhotoPath = employee.PhotoPath
            };
            return View(employeeEditViewModel);
        }

        [HttpPost]
        public IActionResult Edit(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                Employee employee = _employeeRepository.GetEmployee(model.Id);
                ApplicationUser person = _employeeRepository.GetPerson(model.PersonId);
                Position position = _employeeRepository.GetPosition(model.PositionId);
                person.Name = model.Name;
                person.Email = model.Email;
                person.PhoneNumber = model.PhoneNumber;
                person.Gender = model.Gender;
                person.BloodGroup = model.BloodGroup;
                person.BirthDate = model.BirthDate;
                person.PresentAddress = model.PresentAddress;
                person.PermanentAddress = model.PermanentAddress;
                employee.PositionId = model.PositionId;
                employee.PersonId = model.PersonId;
                employee.SpecialtyId = model.SpecialtyId;
                employee.Salary = model.Salary;
                employee.EDate = DateTime.Now;
                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                            "images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }

                    employee.PhotoPath = ProcessUploadedFile(model);
                }

                Employee updatedEmployee = _employeeRepository.Update(employee);
                ApplicationUser updatedPerson = _accountRepository.Update(person);
                //Position updatePosition = _positionRepository.Update(position);

                return RedirectToAction("Index");
            }
            return View(model);
        }
        ///// ekhane image path rename
        private string ProcessUploadedFile(EmployeeViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        #region Doctor Shedule
        [HttpGet]
        [AllowAnonymous]
        public ViewResult CreateDoctorShedule()
        {
            ViewBag.EmployeeList = (from p in _accountRepository.GetAllPerson()
                                    join e in _employeeRepository.GetAllEmployees() on p.Id equals e.PersonId
                                    select new EmployeeViewModel

HospitalMS/Views/Shared/_LayoutDoctor.cshtml
@inject SignInManager<ApplicationUser> SignInManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="img/favicon.png" type="~/image/png">
    <title>@ViewData["Title"] - HospitalMS</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
    </environment>
    <environment exclude="Development">
        @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
            crossorigin="anonymous"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>*@
    </environment>
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link href="~/adminwwwroot/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    @*<link href="~/adminwwwroot/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />*@
    <link href="~/adminwwwroot/css/sb-admin.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/vendors/linericon/style.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendors/lightbox/simpleLightbox.css">
    <link rel="stylesheet" href="~/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="~/vendors/animate-css/animate.css">
    <!-- main css -->
    <link rel="stylesheet" href="~/css/style.css">

</head>
<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark @*static-top*@ fixed-top">

        <a class="navbar-brand logo_h" asp-controller="#" asp-action="#"><img style="height: 56px; width: 65px;" src="~/img/dlogo.png" alt=""></a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            @*<div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>*@
        </form>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">
            @*<li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bell fa-fw"></i>
                        <span class="badge badge-danger">9+</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>*@
            @if (SignInManager.IsSignedIn(User))
            {
                <li class="nav-item">
                    <form method="post" asp-controller="account" asp-action="logout">
                        <button type="submit" style="width:auto"
                                class="nav-link btn btn-link py-0">
                            Logout @User.Identity.Name
                        </button>
                    </form>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="account" asp-action="register">
                        Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="account" asp-action="login">
                        Login
                    </a>
                </li>
            }
            @*<li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-envelope fa-fw"></i>
                        <span class="badge badge-danger">7</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>*@
            @*<li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-circle fa-fw"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="#">Activity Log</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                    </div>
                </li>*@
        </ul>

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav position-fixed" style="    padding-top: 59px;">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="home" asp-action="index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <text>
    @*<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Setup</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Employees" asp-action="CreateDoctorShedule">Appointment Dhedule</a>

                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">Other Pages:</h6>
                <a class="dropdown-item" asp-controller="Administration" asp-action="ListUsers">Manage Users</a>
                <a class="dropdown-item" asp-controller="Administration" asp-action="ListRoles">Manage Roles</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Doctors</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <h6 class="dropdown-header">Login Screens:</h6>
                <a class="dropdown-item" asp-controller="Account" asp-action="Register">Doctor Registeration</a>
                <a class="dropdown-item" asp-controller="Employees" asp-action="Create">Employees</a>
                <a class="dropdown-item" asp-controller="Employees" asp-action="Index">Employee List</a>
                <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">Other Pages:</h6>
                <a class="dropdown-item" href="404.html">404 Page</a>
                <a class="dropdown-item" href="blank.html">Blank Page</a>
            </div>
        </li>*@
</text>

            <li class="nav-item">
                <a class="nav-link"  asp-controller="Doctor" asp-action="Prescription">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Prescription</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span>
                </a>
            </li>
        </ul>

        <div id="content-wrapper">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3" style="padding-top: 38px; padding-left: 10px;  padding-left: 230px;">
                @RenderBody()
            </main>

        </div>
        <!-- /.content-wrapper -->

    </div>



    <!--================ End Header Menu Area =================-->

    <div class="container-fluid" style="padding-left: 0px;padding-right:0px;">

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HospitalMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>*@
    </environment>
    <environment exclude="Development">
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>*@
    </environment>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/stellar.js"></script>
    <script src="~/vendors/lightbox/simpleLightbox.min.js"></script>
    <script src="~/vendors/nice-select/js/jquery.nice-select.min.js"></script>
    <script src="~/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/vendors/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/vendors/counter-up/jquery.counterup.js"></script>
    <script src="~/js/mail-script.js"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="~/js/gmaps.min.js"></script>
    <script src="~/js/theme.js"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: false)
    }
</body>
</html>






@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div>
            @RenderBody()
        </div>
    </body>
    </html>*@